apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tf-workdir-pvc
  namespace: argo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard