apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: tf-demo-workflow
  namespace: argo
spec:
  serviceAccountName: workflow-runner
  entrypoint: main
  hostAliases:
    - ip: "140.82.121.4"  # replace with output of: dig github.com @8.8.8.8 +short
      hostnames:
        - "github.com"
  arguments:
    parameters:
      - name: repo_url
        value: "https://github.com/yogenderPalChandra/argowf-terraform-kind.git"
      - name: revision
        value: "main"
      - name: customer_impersonate_sa
        value: "sa-comcd-deployment@mlops-340210.iam.gserviceaccount.com"
      - name: tf_backend_bucket
        value: "mlops-340210-argowf_tf_state"
      - name: tf_backend_prefix
        value: "state/tf-demo"
      - name: project_id
        value: "mlops-340210"

  templates:
    - name: main
      dag:
        tasks:
          - name: clone
            templateRef:
              name: git-clone
              template: git-clone
            arguments:
              parameters:
                - name: repo_url
                  value: "{{workflow.parameters.repo_url}}"
                - name: revision
                  value: "{{workflow.parameters.revision}}"
                - name: payload
                  value: "{}"
          - name: tf-init
            dependencies: [clone]
            templateRef:
              name: terraform-init
              template: terraform-init
            arguments:
              parameters:
                - name: workdir
                  value: /work/repo
                - name: customer_impersonate_sa
                  value: "{{workflow.parameters.customer_impersonate_sa}}"
                - name: tf_backend_bucket
                  value: "{{workflow.parameters.tf_backend_bucket}}"
                - name: tf_backend_prefix
                  value: "{{workflow.parameters.tf_backend_prefix}}"
          - name: tf-plan
            dependencies: [tf-init]
            templateRef:
              name: terraform-plan
              template: terraform-plan
            arguments:
              parameters:
                - name: workdir
                  value: /work/repo
                - name: customer_impersonate_sa
                  value: "{{workflow.parameters.customer_impersonate_sa}}"
                - name: project_id
                  value: "{{workflow.parameters.project_id}}"
          - name: tf-apply
            dependencies: [tf-plan]
            templateRef:
              name: terraform-apply
              template: terraform-apply
            arguments:
              parameters:
                - name: workdir
                  value: /work/repo
                - name: customer_impersonate_sa
                  value: "{{workflow.parameters.customer_impersonate_sa}}"
                - name: project_id
                  value: "{{workflow.parameters.project_id}}"